from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from . import views

router = DefaultRouter()
router.register(r'reviews', views.ReviewViewSet, basename='review')

urlpatterns = [
    # Auth
    path('auth/register/', views.RegisterView.as_view()),
    path('auth/login/',    TokenObtainPairView.as_view()),
    path('auth/refresh/',  TokenRefreshView.as_view()),
    path('auth/profile/',  views.UserProfileView.as_view()),

    # Teach and Convert — these must live here so they get the /api/ prefix
    path('teach/',   views.TeachView.as_view()),
    path('convert/', views.ConvertView.as_view()),

    # Reviews CRUD (generated by router)
    path('', include(router.urls)),

    # Trigger AI review
    path('reviews/<int:pk>/trigger/', views.TriggerReviewView.as_view()),
]